-   id: clabs_smart_commit
    name: Auto smart commit for jira
    description: Automatically transform your Git commit messages into Jira smart commits
    entry: clabs_smart_commit
    language: python
    stages: [prepare-commit-msg]
    always_run: true